#' Complete cell-level metadata of GBM sample.
#'
#' Cell-level metadata for tutorial use.
#'
#' @format ## `gbm_colData`
#' A data frame with 5,043 rows and 3 columns:
#' \describe{
#'   \item{`cell_type`}{Cell type annotations.}
#'   \item{`umap_1`, `umap_2`}{UMAP embedding derived from gene expression.}
#'   ...
#' }
#' Row names are cell IDs.
#'
#' @source Package tutorial data.
"gbm_colData"

#' Complete transcript-level metadata of GBM sample.
#'
#' Transcript-level metadata for tutorial use. Contains transcript quality control metrics generated by SQANTI3.
#'
#' @format ## `gbm_rowData`
#' A data frame with 56,642 rows and 7 columns:
#' \describe{
#'   \item{`structural_category`}{Structural category of the transcript. One of full-splice_match", "incomplete-splice_match", "novel_in_catalog", "novel_not_in_catalog", "genic", "antisense", "fusion", "intergenic", "genic_intron". (SQANTI3}
#'   \item{`gene_id`}{Associated Ensembl gene ID of the transcript.}
#'   \item{`RTS_stage`}{Logical; `TRUE` if transcript contains one ore more RT switching artifacts. (SQANTI3)}
#'   \item{`within_CAGE_peak`}{Logical; `TRUE` if transcript start site is within a CAGE peak. (SQANTI3)}
#'   \item{`within_polyA_site`}{Logical; `TRUE` if transcript start site is within a polyA site. (SQANTI3)}
#'   \item{`gene_name`}{Associated gene name of the transcript.}
#'   \item{`transcript_name`}{Associated transcript name of the transcript.}
#'   ...
#' }
#' Row names are Ensembl transcript IDs.
#'
#' @source Package tutorial data.
#' "gbm_rowData"

#' Complete single-cell isoform raw count matrix.
#'
#' Matrix containing raw isoform counts for tutorial use.
#'
#' @format ## `gbm_countData`
#' A dgCMatrix with 56,642 rows and 5,043 columns.
#' Row names are Ensembl transcript IDs and column names are cell IDs.
#'
#' @source Package tutorial data.
"gbm_countData"

#' Complete GTF of transcript structural annotations.
#'
#' GRanges object of transcript structural annotations for tutorial use.
#'
#' @format ## `gbm_gtf`
#' A GRanges object with 365,784 ranges and 7 metadata columns.
#'
#' @source Package tutorial data.
"gbm_gtf"
